//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
namespace Midas
{
    using Midas.Utils;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DatabaseContext;
    
    public class BaccaratDBContext : GlobalDBContext
    {
        public BaccaratDBContext()
            : base(StartApp.GlobalConnectionString)
        {

        }
    }
}
