//------------------------------------------------------------------------------
// <auto-generated>
using System.Collections.Generic;

namespace Midas
{  
    public class Session
    {
      
        public Session()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int ID { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public int Result2Threads { get; set; }
        public int Result4Threads { get; set; }
        public int NoOfSteps { get; set; }   
       
        public virtual ICollection<Result> Results { get; set; }
    }
}
